apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app
  namespace: argocd

spec:
  project: default

  source:
    # Your GitHub Pages Helm Repository
    repoURL: https://Gowrish006.github.io/E-Commerce-app-new
    chart: ecommerce-app
    targetRevision: "*"   # deploy latest chart version
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
